// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"

enum class EV3DCmd : uint8;

/**
 * 
 */
class SPACEMOUSEREADER_API FButtons
{
public:
    FButtons();
    ~FButtons();
};

enum class EV3DCmd : uint8
{
    Noop                             = 0,
    MenuOptions                      = 1,
    ViewFit                          = 2,
    ViewTop                          = 3,
    ViewLeft                         = 4,
    ViewRight                        = 5,
    ViewFront                        = 6,
    ViewBottom                       = 7,
    ViewBack                         = 8,
    ViewRollcw                       = 9,
    ViewRollccw                      = 10,
    ViewIso1                         = 11,
    ViewIso2                         = 12,
    KeyF1                            = 13,
    KeyF2                            = 14,
    KeyF3                            = 15,
    KeyF4                            = 16,
    KeyF5                            = 17,
    KeyF6                            = 18,
    KeyF7                            = 19,
    KeyF8                            = 20,
    KeyF9                            = 21,
    KeyF10                           = 22,
    KeyF11                           = 23,
    KeyF12                           = 24,
    KeyEsc                           = 25,
    KeyAlt                           = 26,
    KeyShift                         = 27,
    KeyCtrl                          = 28,
    FilterRotate                     = 29,
    FilterPanzoom                    = 30,
    FilterDominant                   = 31,
    ScalePlus                        = 32,
    ScaleMinus                       = 33,
    ViewSpincw                       = 34,
    ViewSpinccw                      = 35,
    ViewTiltcw                       = 36,
    ViewTiltccw                      = 37,
    MenuPopup                        = 38,
    MenuButtonmappingeditor          = 39,
    MenuAdvancedsettingseditor       = 40,
    MotionmacroZoom                  = 41,
    MotionmacroZoomoutCursorToCenter = 42,
    MotionmacroZoominCursorToCenter  = 43,
    MotionmacroZoomoutCenterToCenter = 44,
    MotionmacroZoominCenterToCenter  = 45,
    MotionmacroZoomoutCursorToCursor = 46,
    MotionmacroZoominCursorToCursor  = 47,
    ViewQzIn                         = 48,
    ViewQzOut                        = 49,
    KeyEnter                         = 50,
    KeyDelete                        = 51,
    KeyF13                           = 52,
    KeyF14                           = 53,
    KeyF15                           = 54,
    KeyF16                           = 55,
    KeyF17                           = 56,
    KeyF18                           = 57,
    KeyF19                           = 58,
    KeyF20                           = 59,
    KeyF21                           = 60,
    KeyF22                           = 61,
    KeyF23                           = 62,
    KeyF24                           = 63,
    KeyF25                           = 64,
    KeyF26                           = 65,
    KeyF27                           = 66,
    KeyF28                           = 67,
    KeyF29                           = 68,
    KeyF30                           = 69,
    KeyF31                           = 70,
    KeyF32                           = 71,
    KeyF33                           = 72,
    KeyF34                           = 73,
    KeyF35                           = 74,
    KeyF36                           = 75,
    View1                            = 76,
    View2                            = 77,
    View3                            = 78,
    View4                            = 79,
    View5                            = 80,
    View6                            = 81,
    View7                            = 82,
    View8                            = 83,
    View9                            = 84,
    View10                           = 85,
    View11                           = 86,
    View12                           = 87,
    View13                           = 88,
    View14                           = 89,
    View15                           = 90,
    View16                           = 91,
    View17                           = 92,
    View18                           = 93,
    View19                           = 94,
    View20                           = 95,
    View21                           = 96,
    View22                           = 97,
    View23                           = 98,
    View24                           = 99,
    View25                           = 100,
    View26                           = 101,
    View27                           = 102,
    View28                           = 103,
    View29                           = 104,
    View30                           = 105,
    View31                           = 106,
    View32                           = 107,
    View33                           = 108,
    View34                           = 109,
    View35                           = 110,
    View36                           = 111,
    SaveView1                        = 112,
    SaveView2                        = 113,
    SaveView3                        = 114,
    SaveView4                        = 115,
    SaveView5                        = 116,
    SaveView6                        = 117,
    SaveView7                        = 118,
    SaveView8                        = 119,
    SaveView9                        = 120,
    SaveView10                       = 121,
    SaveView11                       = 122,
    SaveView12                       = 123,
    SaveView13                       = 124,
    SaveView14                       = 125,
    SaveView15                       = 126,
    SaveView16                       = 127,
    SaveView17                       = 128,
    SaveView18                       = 129,
    SaveView19                       = 130,
    SaveView20                       = 131,
    SaveView21                       = 132,
    SaveView22                       = 133,
    SaveView23                       = 134,
    SaveView24                       = 135,
    SaveView25                       = 136,
    SaveView26                       = 137,
    SaveView27                       = 138,
    SaveView28                       = 139,
    SaveView29                       = 140,
    SaveView30                       = 141,
    SaveView31                       = 142,
    SaveView32                       = 143,
    SaveView33                       = 144,
    SaveView34                       = 145,
    SaveView35                       = 146,
    SaveView36                       = 147,
    KeyTab                           = 148,
    KeySpace                         = 149,
    Menu1                            = 150,
    Menu2                            = 151,
    Menu3                            = 152,
    Menu4                            = 153,
    Menu5                            = 154,
    Menu6                            = 155,
    Menu7                            = 156,
    Menu8                            = 157,
    Menu9                            = 158,
    Menu10                           = 159,
    Menu11                           = 160,
    Menu12                           = 161,
    Menu13                           = 162,
    Menu14                           = 163,
    Menu15                           = 164,
    Menu16                           = 165,
};

